# Generated by Django 3.0.4 on 2020-04-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y2017', models.BooleanField(default=False, verbose_name='2017')),
                ('y2018', models.BooleanField(default=False, verbose_name='2018')),
                ('y2019', models.BooleanField(default=False, verbose_name='2019')),
                ('y2020', models.BooleanField(default=False, verbose_name='2020')),
            ],
        ),
    ]
