# Generated by Django 3.0.4 on 2020-03-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=50)),
                ('problem_text', models.TextField(max_length=1500)),
                ('address', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
